name: Build and Package

on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build for Windows
        run: dotnet build --configuration Release --output ./bin/Windows

  build_linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build for Linux
        run: dotnet publish -c Release -r linux-x64 --output ./bin/Linux
  
  #package:
  #  name: Package Builds
  #  runs-on: ubuntu-latest
  #  needs: [build_windows, build_linux]
  #  steps:
  #    - name: Create Output Directory
  #      run: mkdir -p ./output
#
  #    - name: Copy Windows build
  #      run: cp -r ./bin/Windows ./output/Windows
#
  #    - name: Copy Linux build
  #      run: cp -r ./bin/Linux ./output/Linux
#